site_name: Architecture Numérique et VHDL
site_url: https://pjlapray.github.io/Site_web/
repo_url: https://github.com/pjlapray/Site_web
repo_name: pjlapray/Site_web
edit_uri: edit/main/docs/

theme:
  name: material
  language: fr
  features:
    - navigation.tabs      # Active le menu horizontal en haut
    - navigation.sections  # Titres de sections à gauche
    - navigation.expand    # Déroule le menu par défaut
    - navigation.top       # Bouton retour en haut
    - search.suggest
    - content.code.copy    # Bouton copier pour le code VHDL
    
  palette:
    - scheme: default
      primary: white
      accent: blue
      toggle:
        icon: material/brightness-7
        name: Mode sombre
    - scheme: slate
      primary: grey
      accent: blue
      toggle:
        icon: material/brightness-4
        name: Mode clair

  font:
    text: Roboto
    code: Roboto Mono

# Définition des onglets du haut et de leurs pages
nav:
  - Accueil: index.md
  - "Electronique Numérique":
      - Introduction: en/intro.md
      - Logique Combinatoire: en/logique_combinatoire.md
      - Logique Séquentielle: en/logique_sequentielle.md
  - "Syst. Emb. Reconfig. 1":
      - Introduction VHDL: ser1/intro.md
  - "Syst. Emb. Reconfig. 2":
      - Introduction SoC-FPGA: ser2/intro.md

extra_css:
  - css/custom.css

extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.7/MathJax.js?config=TeX-MML-AM_CHTML

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      pygments_lang_class: true
  - pymdownx.superfences
  - pymdownx.arithmatex:
      generic: true
  - admonition
  - pymdownx.details
  - toc:
      permalink: true