site_name: Systèmes embarqués Reconfigurables
site_url: https://pjlapray.github.io/Site_web/
repo_url: https://github.com/pjlapray/Site_web
repo_name: "P-J. Lapray"
edit_uri: edit/main/docs/

theme:
  name: material
  language: fr
  
  # Configuration des images (doivent être dans docs/assets/)
  logo: assets/logo.png
  favicon: assets/favicon.png
  
  features:
    - navigation.tabs      # Active les onglets horizontaux
    - navigation.sections  # Titres de sections à gauche
    - navigation.expand    # Menu de gauche ouvert par défaut
    - navigation.top       # Bouton de retour en haut
    - search.suggest
    - content.code.copy    # Bouton de copie pour le code VHDL
    
  palette:
    - scheme: default
      primary: white
      accent: blue
      toggle:
        icon: material/brightness-7
        name: Mode sombre
    - scheme: slate
      primary: grey
      accent: blue
      toggle:
        icon: material/brightness-4
        name: Mode clair

  font:
    text: Roboto
    code: Roboto Mono

# Définition de la navigation (vos 3 onglets)
nav:
  - Accueil: index.md
  - "Electronique Numérique":
      - Introduction: en/intro.md
      - Logique Combinatoire: en/logique_combinatoire.md
      - Logique Séquentielle: en/logique_sequentielle.md
  - "Syst. Emb. Reconfig. 1":
      - Introduction VHDL: ser1/intro.md
  - "Syst. Emb. Reconfig. 2":
      - Introduction SoC-FPGA: ser2/intro.md

extra_css:
  - css/custom.css

extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.7/MathJax.js?config=TeX-MML-AM_CHTML
      
markdown_extensions:
  - attr_list
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
      pygments_lang_class: true
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.emoji:
      emoji_index: !!python/name:pymdownx.emoji.twemoji
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
      