site_name: Architecture Numérique et VHDL
site_url: https://pjlapray.github.io/Site_web/
repo_url: https://github.com/pjlapray/Site_web
repo_name: "P-J. Lapray"

theme:
  name: material
  language: fr
  logo: assets/logo.png
  favicon: assets/favicon.png
  
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.top
    - search.suggest
    - content.code.copy
    
  palette:
    - scheme: default
      primary: white
      accent: blue
      toggle:
        icon: material/brightness-7
        name: Mode sombre
    - scheme: slate
      primary: grey
      accent: blue
      toggle:
        icon: material/brightness-4
        name: Mode clair

nav:
  - Accueil: index.md
  - "Electronique Numérique":
      - Introduction: en/intro.md
      - Logique Combinatoire: en/logique_combinatoire.md
      - Logique Séquentielle: en/logique_sequentielle.md
  - "Syst. Emb. Reconfig. 1":
      - Introduction VHDL: ser1/intro.md
  - "Syst. Emb. Reconfig. 2":
      - Introduction SoC-FPGA: ser2/intro.md

markdown_extensions:
  - attr_list
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
      pygments_lang_class: true
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.emoji:
      emoji_index: !!python/name:pymdownx.emoji.twemoji
      emoji_generator: !!python/name:pymdownx.emoji.to_svg